#!/usr/bin/env bash

wikidir="/usr/share/doc/arch-wiki/html/en/"
wikidocs="$(find ${wikidir} -iname "*.html")"
menu="dmenu -l 10 -i -p"
browser="librewolf"
main(){
    choice=$(printf '%s\n' "${wikidocs[@]}" | \
        cut -d '/' -f8- | \
        sed -e 's/_/ /g' -e 's/.html//g' | \
        sort | ${menu} 'Search Wiki: ' "$@") || exit 1

    if [ "$choice" ]; then
        article=$(printf '%s\n' "${wikidir}${choice}.html" | sed 's/ /_/g')
        "${browser}" "${article}"
    else
        echo "Program terminated." && exit 0
    fi
}
main "$@"
